timezone: Asia/Shanghai
portlet:
  version: 1.0.1
  name: account
  layout: main
  language: en
  dependsOn:
    - common
  redirects:
    '/': 'menu://main'
    '/users' : 'menu://main/settings/users'
    '/login': '/@account/login'
    '/logout': '/@account/logout'
