logger:
  level: debug
  console: {}
portlet:
  port: 18002
  mock: true
  debug: true
  compress: true
  logRoutes: true
  logRequests: true
  uploadDir: '{{root}}/mnt/uploads'
  storages:
    # avatar: 
    #   type: local
    #   options:
    #     root: '{{root}}/mnt/storage'
    #   bucket: 'main'
    #   prefix: 'avatar/'
    #   cacheDir: '{{root}}/mnt/cache'
    avatar: 
      type: minio
      options:
        endPoint: 127.0.0.1
        port: 9000
        useSSL: false
        accessKey: minioadmin
        secretKey: minioadmin
      bucket: 'account'
      prefix: 'avatar/'
      cacheDir: '{{root}}/mnt/cache'
  passport:
    jwt:
      expiration: 24h
  selfUrl: localhost:18002
  discovery:
    url: localhost:18000